server:
  port: 8080
  
# neo4j配置
spring:
  application:
    name: boot_neo4j
  neo4j:
    uri: bolt://127.0.0.1:7687
    pool:
      metrics-enabled: true
      log-leaked-sessions: true
    authentication:
      username: neo4j
      password: neo4jneo4j
      
  data:
    neo4j:
      repositories:
        type: auto
      database: neo4j
logging:
  level:
    org.springframework.data.neo4j: DEBUG
    